config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get "admin", to:"admins#admin_home", as: "admin_home"
  get "admin/transactions", to:"admins#transactions", as: "transactions_all"
  get "admin/users", to:"users#index", as: "users_all"
  post "admin/users", to:"users#create", as: "create_user"
  delete "admin/users/:id", to:"users#destroy", as: "destroy_user"
  get "admin/users/:id/edit", to:"users#edit", as: "edit_user"
  patch "admin/users/:id/edit", to:"users#update", as: "update_user"
  get "admin/users/new", to:"users#new", as: "new_user"
  patch "admin/users/:id/approve", to:"users#approve", as: "approve_user"

  devise_for :users
  root to: "transactions#new", as: "home"
  get "crypto", to: "transactions#new_crypto", as: "crypto"
  resources :transactions, except: [:new]
  resources :stocks
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :transactions, :dependent => :destroy
  has_many :stocks, :dependent => :destroy

  def buy_stock!(volume, stock)
    symbol = stock
    volume = volume.to_i
    stock = self.stocks.find_by symbol: symbol
    transaction = transactions.build(
      volume:volume,
      stock: symbol,
      method: "Buy",
      price: IEX_CLIENT.quote(symbol).latest_price
    )
    if stock
      stock.volume += volume
      stock.average_price = (stock.average_price * stock.volume + transaction.price * transaction.volume) / (stock.volume + transaction.volume)
    else
      stock = stocks.build(symbol: transaction.stock, average_price: transaction.price, volume: transaction.volume)
    end

    ActiveRecord::Base.transaction do
      transaction.save!
      stock.save!
    end
  end

  def sell_stock!(volume, stock)
    symbol = stock
    volume = volume.to_i
    stock = self.stocks.find_by symbol: symbol
    transaction = transactions.build(
      volume:volume,
      stock: symbol,
      method: "Sell",
      price: IEX_CLIENT.quote(symbol).latest_price
    )
    if stock
      if stock.volume >= volume
        stock.volume -= transaction.volume
        ActiveRecord::Base.transaction do
          transaction.save!
          if stock.volume == 0
            stock.destroy
          else
            stock.save!
          end
        end
      else
        raise ArgumentError.new("You do not own enough shares of this stock")
      end
    else
      raise ArgumentError.new("You do not own shares of this stock")
    end
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    before_action :authenticate_admin!
    
    def admin_home

    end

    def transactions
        @transactions = Transaction.all
    end

    def users
        @users = User.all
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :authenticate_user!
    def index
        @stocks = current_user.stocks
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :redirect_to_admin, only: %i[new new_crypto]
    before_action :authenticate_user!
    before_action :check_if_user_approved, only: %i[create]
    before_action :transaction_params, only: %i[create]
    
    def index
        @transactions = current_user.transactions
    end

    def new
        @transaction = Transaction.new
        symbol = params["symbol"] ? params["symbol"] : ""
        if SYMBOLS.include? symbol 
            @stock_data = IEX_CLIENT.quote(symbol)
        end
    end

    def new_crypto
        @transaction = Transaction.new
        crypto = Crypto.new
        @crypto_symbols = crypto.crypto_symbols

        symbol = params["symbol"] ? params["symbol"] : ""
        if @crypto_symbols.include? symbol 
            @crypto_data = crypto.quote_crypto(symbol).first
        end

        quote_all = params["all"] ? true : false
        if symbol && quote_all
            @quotes = crypto.quote_crypto_on_all_rates(symbol)
        end
    end
    def create
        begin
            if params[:method]== "Buy"
                current_user.buy_stock!(transaction_params[:volume], transaction_params[:stock])
                redirect_to transactions_url, notice: "Stock was successfully bought"
            elsif params[:method]== "Sell"
                current_user.sell_stock!(transaction_params[:volume], transaction_params[:stock])
                redirect_to transactions_url, notice: "Stock was succesfully sold"
            end
        rescue ArgumentError => e
            redirect_to transactions_url, notice: e.message
        rescue ActiveRecord::ValidationError
            redirect_to transactoins_url, notice: "Error in executing transaction. Contact admin."
        end
    end

    private

    def transaction_params
        params.require(:transaction).permit(:volume, :stock, :method)
    end

    def redirect_to_admin
        if admin_signed_in?
            redirect_to admin_home_url
        end
    end

    def check_if_user_approved
        if current_user.approved != true
            redirect_to home_path, notice: "User must be approved to make transactions"
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_user, only: %i[update show edit destroy approve]
    before_action :user_params, only: %i[update create]
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def edit
    end

    def update

        if @user.valid_password?(user_params[:current_password])
            if @user.update(email: user_params[:email], password: user_params[:password], password_confirmation: user_params[:password_confirmation])
                redirect_to users_all_path
            else
                render 'edit'
            end
        else
            redirect_to edit_user_path(@user), notice:"Current password is incorrect"
        end
    end

    def create
        if User.create(email: user_params[:email], password: user_params[:password], password_confirmation: user_params[:password_confirmation])
            redirect_to users_all_path, notice: "User has been created"
        end
    end

    def destroy
        if @user.destroy
            redirect_to users_all_path, notice: "User was successfully destroyed"
        end
    end

    def approve
        if @user.update(approved: true)
            AdminMailer.admin_approval(@user).deliver_now
            redirect_to users_all_path, notice: "#{@user.email} has been approved"
        else
            redirect_to users_all_path, notice: "#{@user.email} approval error"
        end
    end

    private

    def set_user
        @user = User.find_by(id:params[:id])
    end

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/admin_home.html.erb
<h1 class="p-4"> Welcome to the Admin Account. </h1>

app/views/admins/transactions.html.erb
<table>
    <tr>
        <th class="pl-2 pr-2 text-center"> User ID </th>
        <th class="pl-2 pr-2 text-center"> User email </th>
        <th class="pl-2 pr-2 text-center">Stock</th>
        <th class="pl-2 pr-2 text-center">Price</th>
        <th class="pl-2 pr-2 text-center">Volume</th>
        <th class="pl-2 pr-2 text-center">Amount</th>
        <th class="pl-2 pr-2 text-center">Action</th>
        <th class="pl-2 pr-2 text-center">DateTime</th>
    </tr>

    <% @transactions.each do |transaction| %>
        <tr>
            <td class="pl-2 pr-2 text-center"><%= transaction.user_id %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.user.email %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.stock %> </td>
            <td class="pl-2 pr-2 text-center">$<%= transaction.price %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.volume %> </td>
            <td class="pl-2 pr-2 text-center"><%= "$" +(transaction.volume * transaction.price).round(2).to_s %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.method %> </td>
            <td class="pl-2 pr-2 text-center text-xs"><%= transaction.created_at %> </td>
        </tr>
    <% end %>
</table

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex items-center flex-col">
    <% if admin_signed_in? %>
      <nav class="w-full flex p-3 items-center">
        <div class="w-full flex items-center">
          <%= link_to "STOCKS ADMIN", admin_home_path, class: "text-2xl text-blue-900 pr-2 pl-2"%>
          <%= link_to "All Users", users_all_path, class: "text-blue-500 pr-2 pl-2 hover:text-blue-200"%>
          <%= link_to "Transactions", transactions_all_path, class: "text-blue-500 pr-2 pl-2 hover:text-blue-200"%>
        </div>
        <%= link_to "Logout", destroy_admin_session_path, method: :delete , class:"text-blue-900 hover:text-blue-200"%>
      </nav>
    <% elsif user_signed_in? %>
      <nav class="w-full flex justify-between">
        <div class="flex p-4 items-center">
          <%= link_to "STOCKS", home_path, class: "text-2xl text-blue-900 pr-2 pl-2"%>
          <%= link_to "Portfolio", stocks_path, class: "text-blue-500 pr-2 pl-2 hover:text-blue-200"%>
          <%= link_to "Transactions", transactions_path,class: "text-blue-500 pr-2 pl-2 hover:text-blue-200"%>
        </div>
        <div class="flex flex-col p-4">
          <p> Logged in as <strong><%= current_user.email %></strong>. </p>
          <div class="flex justify-end">
            <%= link_to 'Edit profile', edit_user_registration_path %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          </div>
        </div>
      </nav>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="h-5/6 max-w-7xl w-7/12 bg-slate-300 rounded-md flex flex-col items-center mt-5 overflow-scroll">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/index.html.erb
<table class= "m-4">
    <tr>
        <th class="pl-2 pr-2 text-center">Stock</th>
        <th class="pl-2 pr-2 text-center">Average Price</th>
        <th class="pl-2 pr-2 text-center">Volume</th>
        <th class="pl-2 pr-2 text-center">Amount</th>
 
    </tr>

    <% @stocks.each do |stock| %>
        <tr>
            <td class="pl-2 pr-2 text-center"><%= stock.symbol%> </td>
            <td class="pl-2 pr-2 text-center">$<%= stock.average_price %> </td>
            <td class="pl-2 pr-2 text-center"><%= stock.volume %> </td>
            <td class="pl-2 pr-2 text-center">$<%= (stock.volume * stock.average_price).round(2) %> </td>
        </tr>
    <% end %>
</table

app/views/transactions/index.html.erb
<table>
    <tr>
        <th class="pl-2 pr-2 text-center">Stock</th>
        <th class="pl-2 pr-2 text-center">Price</th>
        <th class="pl-2 pr-2 text-center">Volume</th>
        <th class="pl-2 pr-2 text-center">Amount</th>
        <th class="pl-2 pr-2 text-center">Action</th>
        <th class="pl-2 pr-2 text-center">DateTime</th>
    </tr>

    <% @transactions.each do |transaction| %>
        <tr>
            <td class="pl-2 pr-2 text-center"><%= transaction.stock %> </td>
            <td class="pl-2 pr-2 text-center">$<%= transaction.price %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.volume %> </td>
            <td class="pl-2 pr-2 text-center"><%= "$" +(transaction.volume * transaction.price).round(2).to_s %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.method %> </td>
            <td class="pl-2 pr-2 text-center"><%= transaction.created_at %> </td>
        </tr>
    <% end %>
</table

app/views/transactions/new.html.erb
<% if @stock_data %>
  <div class="border-slate-400 flex flex-col w-full p-4 pl-10">
    <h1 class="text-lg font-bold"><%=@stock_data.symbol%></h1>
    <h2><%=@stock_data.company_name%></h2>
    <h2>$ <%=@stock_data.latest_price%></h2>
    <h2><%=@stock_data.change_percent_s%></h2>
  </div>
<% end %>
<%= form_with(model: @transaction) do |form| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transactions.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="font-bold mt-8 ml-12">
    <%= form.label :stock, "Stock" %>
    <%= form.select :stock , options_for_select(SYMBOLS, @stock_data ? @stock_data.symbol : SYMBOLS.first), :id => "show_stock"  %>
    <%= link_to "Quote", home_path(:symbol => ""), :id=>"quote_link" , class:"text-blue-700 hover:text-blue-300"%>
    <%= javascript_pack_tag "show_symbol" %>
  </div>
  
  <div class="font-bold mt-8 ml-12">
    <%= form.label :volume, "Volume" %>
    <%= form.number_field :volume%>
  </div>

  <div class="flex">
    <div class="flex justify-center items-center text-white font-bold m-3 mt-5 bg-green-400 hover:bg-green-200 hover:text-black p-4 rounded-md w-36 h-12 ">
      <%= form.submit "Buy", :name => :method %>
    </div>

    <div class="flex justify-center items-center text-white font-bold m-3 mt-5 bg-red-400 hover:bg-red-200 hover:text-black p-4 rounded-md w-36 h-12 ">
      <%= form.submit "Sell", :name => :method%>
    </div>
  </div>

<% end %>

app/views/transactions/new_crypto.html.erb
<% if @crypto_data %>
  <div class="border-slate-400 flex flex-col w-full p-4 pl-10">
    <h1 class="text-lg font-bold"><%=@crypto_data["asset_id"]%></h1>
    <h2><%=@crypto_data["name"]%></h2>
    <h2>$ <%=@crypto_data["price_usd"]%></h2>
  </div>
<% end %>


<%= form_with(model: @transaction) do |form| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transactions.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% @transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="font-bold mt-8 ml-12">
    <%= form.label :stock, "Crypto" %>
    <%= form.select :stock , options_for_select(@crypto_symbols, @crypto_data ? @crypto_data["asset_id"] : @crypto_symbols.first), :id => "show_stock"  %>
    <%= link_to "Quote", crypto_path(:symbol => ""), :id=>"quote_link" , class:"text-blue-700 hover:text-blue-300"%>  | 
    <%= link_to "Quote all rates", crypto_path(:symbol=> "", :all=>1), :id=>"quote_all_link", class:"text-blue-700 hover:text-blue-300"%>
    <%= javascript_pack_tag "show_symbol" %>
  </div>

<% end %>
<% if @quotes%>
    <div class="flex flex-wrap justify-center w-full">
        <% @quotes.each do |quote| %>
            <div class="w-1/5 h-40 m-2 border-2 rounded-md text-md">
                <h1 class="font-bold text-sm"><%= quote["asset_id_quote"]%></h1>
                <h2><%= quote["rate"].round(2) %></h2>
            </div>
        <% end %>
    </div>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model:@user, url:edit_user_path) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<div class="w-full p-3 ml-10 font-bold text-blue-900 hover:text-blue-400">
    <%= link_to "+ Add New User", new_user_path %>
</div>
<table>
    <tr>
        <th class="pl-2 pr-2 text-center"> User ID </th>
        <th class="pl-2 pr-2 text-center"> User email </th>
        <th class="pl-2 pr-2 text-center"> Approved ?</th>
        <th class="pl-2 pr-2 text-center"> Actions</th>
    </tr>

    <% @users.each do |user| %>
        <tr>
            <td class="pl-2 pr-2 text-center"><%= user.id%> </td>
            <td class="pl-2 pr-2 text-center"><%= user.email%> </td>
            <td class="pl-2 pr-2 text-center"><%= user.approved ?  "✓" : "Pending" %> </td>
            <td class="pl-2 pr-2 text-center">
                <% if !user.approved %> 
                    <%= link_to "Approve", approve_user_path(user.id), method: "patch", class:"pl-1 text-blue-500 hover:text-blue-300"%> |
                <% end %>
                <%= link_to "Edit", edit_user_path(user.id), class:"pl-1 text-blue-500 hover:text-blue-300"%> |
                <%= link_to "Destroy", destroy_user_path(user.id), method: "delete", class:"pl-1 text-blue-500 hover:text-blue-300"%>
            </td>
        </tr>
    <% end %>
</table

app/views/users/new.html.erb
<%= form_with(model:@user, url:create_user_path) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to "Back", :back %>